name: Sync configuration

on:
  push:
    branches:
      - main
    paths:
      - 'stations.json'
  workflow_dispatch:

jobs:
  deploy-encoders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up SSH Keys
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Generate encoders
        run: node createEncoders.js

      - name: Sync encoders
        run: |
          rsync -avz --delete ./encoders/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/${{ secrets.ENCODERS_CONF_PATH }}

      - name: Reload encoders
        run: ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} 'supervisorctl reread && supervisorctl update'

  build-mux:
    needs: deploy-encoders
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Update mux file
        run: node updateMux.js

      - name: Commit and push if changed
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add mux.json
          git commit -m "Update mux with new or changed stations" -a || echo "No changes to commit"
          git push
