name: Sync configuration

on:
  push:
    branches:
      - main
    paths:
      - 'stations.json'
  workflow_dispatch:

jobs:
  deploy-encoders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up SSH Keys
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Generate directory structure
        run: |
          node generator-dirs.js | ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} 'xargs -I {} mkdir -p "{}"'

      - name: Generate encoders
        run: node generator-encoders.js

      - name: Sync encoders
        run: |
          rsync -avz --delete ./encoders/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/${{ secrets.ENCODERS_CONF_PATH }}

      - name: Reload encoders
        run: ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} 'supervisorctl reread && supervisorctl update'

  build-mux:
    needs: deploy-encoders
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up SSH Keys
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Generate mux file
        run: node generator-mux.js

      - name: Commit new mux to GitHub
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add mux.json
          git commit -m "New mux with updated stations" -a || echo "No changes to commit"
          git push

      - name: Check if mux.json changed
        id: check_mux_changed
        run: |
          if [[ $(git rev-list --count HEAD) -gt 1 ]]; then
            CHANGED=$(git diff --name-only HEAD HEAD~1 | grep -w mux.json | wc -l)
          else
            CHANGED=0
          fi
          echo "MUX_CHANGED=$CHANGED" >> $GITHUB_ENV
          if [[ "$CHANGED" -eq "1" ]]; then
            echo "Mux has changed. Running sync steps."
          else
            echo "Mux has not changed. Skipping sync steps."
          fi

      - name: Sync mux to server
        if: env.MUX_CHANGED == '1'
        run: |
          rsync -avz --delete mux.json ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/var/dab/mux/mux.json

      - name: Schedule mux restart
        if: env.MUX_CHANGED == '1'
        run: ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} 'touch /tmp/.restart-mux-needed'
